# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: jinho.dev"

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: "UA-146894545-1"

menu:
  - { name: "Development", folder: "pages", file: "facts.html" }
  - { name: "Book Review", folder: "pages", file: "resources.html" }
  - { name: "Resume", folder: "pages", file: "documentation.html" }
  - { name: "About", folder: "pages", file: "about.html" }
  - { name: "Contact", folder: "pages", file: "contact.html" }

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - { icon: "github", link: "https://github.com/jinhokongm" }
  - {
      icon: "linkedin",
      link: "https://www.linkedin.com/in/jinho-hong-a9693a134/",
    }
  - {
      icon: "facebook",
      link: "https://www.facebook.com/kongkongkongkongkongkongkongkong",
    }
  - { icon: "envelope", link: "mailto:tpdleps@gmail.com" }

# Customize site text
pagination:
  next_page: "Newer"
  previous_page: "Older"

sharing_button_prompt: "Feel free to share!"

related_posts: "You may also enjoy..."

post_date_prefix: "Written on"
